name: torch251
channels:
  - conda-forge
  - defaults
dependencies:
  # Core data handling
  - pandas>=2.0
  - numpy>=1.24

  # Text cleaning & NLP
  - emoji>=2.8
  - nltk>=3.9
  - scikit-learn>=1.3
  - isodate>=0.6
  - pip  # keep pip for some pip-only deps

  # Visualization
  - matplotlib>=3.7
  - seaborn>=0.12
  - wordcloud>=1.9

  # Deep learning / embeddings
  - pip:
      - transformers>=4.42
      - sentence-transformers>=3.0
      - accelerate>=0.33
